In [1]:
import math

import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [5]:
x.size()

torch.Size([12])

In [7]:
x.numel()

12

In [8]:
x.numpy()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [12]:
X = x.reshape(3, 4)

In [13]:
X.size()

torch.Size([3, 4])

In [14]:
X.shape

torch.Size([3, 4])

In [15]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [17]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [18]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [19]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [21]:
torch.exp(y)

tensor([7.3891, 7.3891, 7.3891, 7.3891])

In [23]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [25]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [34]:
X.sum(), Y.sum()

(tensor(66.), tensor(30.))

In [36]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [38]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [41]:
a * b

tensor([[0, 0],
        [0, 1],
        [0, 2]])

In [44]:
X[-1], X[1: 3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [47]:
X[1, 1] = 10
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4., 10.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [48]:
X[1:2, :] = 100
X

tensor([[  0.,   1.,   2.,   3.],
        [100., 100., 100., 100.],
        [  8.,   9.,  10.,  11.]])

In [49]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [58]:
Z = torch.ones_like(Y)
print(Z)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
id(Z): 1785199694432
id(Z): 1785199694432


In [59]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [18]:
# 求半径为10的圆与半径为5的圆，他们的周长和面积之差，结果全部保留整数部分，并将周长之差存储到数组q6中，面积之差存储到数组q7中
q6 = int(2 * 3.14 * (10 - 5))
q7 = int(3.14 * (10 ** 2 - 5 ** 2))
q6, q7

(31, 235)

In [21]:
# 判断2008是否是闰年，结果保存到数组q8中，闰年输出True，平年输出False
if 2008 % 4 == 0:
    q8 = 'True'
else:
    q8 = 'False'

True


In [24]:
# 写一个if else语句判断输入的是英寸还是厘米，并输出相对应的另一个值；如输入100厘米，则输出39英寸；题目要求如下：
# （1）定义一个列表变量，取名q1，先后保存输出的值；
# （2）使用input先后判断长度和单位；
# （3）先后输出15英寸对应多少厘米，40厘米对应多少英寸，全部结果保留整数部分，并将最终结果保存到列表q1中（使用append()函数）；
# （4）由于还没有学循环函数，所以这里先不加循环，运行两遍得到结果即可，别忘使用append()函数把每次运行的答案加入到数组q1中；
q1 = []
for _ in range(2):
    temp1 = input('dw')
    temp2 = int(input('cd'))
    if temp1 == '英寸':
        q1.append(int(temp2 * 0.39))
    elif temp1 == '厘米':
        q1.append(int(temp2 / 0.39))

In [25]:
# 写一个分支结构判断输入的成绩对应的等级多少？如果在90分以上（含90分）输出A；80分-90分（不含90分）输出B；70分-80分（不含80分）输出C；60分-70分（不含70分）输出D；60分以下输出E。题目要求如下：
# （1）假如小明，小张和小王同学在期末考试分别考了79分、90分以及89分，请判断他们三个对应的成绩等级是多少？使用input函数分别输入并输出；
# （2）定义一个数组q2，分别保存三位同学的成绩等级，形式如['A', 'B', 'C']这种；
# （3）如果有同学提前学过循环，可以尝试用循环来做，没学过的同学也不要着急，第四关就会学到，这里可以先后输入三个成绩然后运行三遍程序即可得到答案，每运行一次要使用append函数加入到数组q2中；
q2 = []
for _ in range(3):
    temp = eval(input('score'))
    if temp >= 90:
        q2.append('A')
        continue
    elif temp > 80:
        q2.append('B')
        continue
    elif temp > 70:
        q2.append('C')
        continue
    elif temp > 60:
        q2.append('D')
        continue
    else:
        q2.append('E')


In [26]:
q2

['C', 'A', 'B']

写一个分支结构判断输入给定的三组值能否构成三角形，题目要求如下：

（1）给定三组值，分别为[6,10,9]，[9,16,25]，[13,12,5]，，判断这三组值能否构成三角形。

（2）如果能构成三角形，则输出该三角形周长和面积，如果不能，输出no。【注意：周长和面积只保留整数部分】

（3）定义一个数组q3，如果可以构成三角形，则将该三角形的周长和面积（注意顺序）加入到数组q3中，如果不能构成 ，则向数组中加入no，注意按照给定的组顺序来保存。比如第一组和第三组不能构成，第二组可以构成，则q3=['no', 第二组周长值, 第二组面积值, 'no']；

In [42]:
q1 = []


def judge():
    temp = eval(input('input'))
    for i in range(2, temp // 2):
        if temp % i == 0:
            a = 'no'
            break
        a = 'yes'
    # return a


q1.append(judge())
q1

['no']

In [7]:
temp1 = 20
temp2 = 16


def max_yue(x, y):
    (x, y) = (y, x) if y > x else (x, y)
    for i in range(x, 0, -1):
        if x % i == 0 and y % i == 0:
            return i


def max_bei(x, y):
    return int(x * y / max_yue(x, y))


q3 = [max_yue(temp1, temp2), max_bei(temp1, temp2)]
q3

[4, 80]

假设a=log(3)/3，b=log(5)/5，比较这两个数的大小，如果a>b，则输出大于，如果a<b，则输出小于；将最终结果是大于还是小于保存到数组q1中；

In [11]:
def compare():
    if math.log(3) / 3 > math.log(5) / 5:
        q1.append('大于')
    else:
        q1.append('小于')


q1

NameError: name 'q1' is not defined

In [18]:
a = 8
b = 3
x1 = round(float(((a + b) * (a - b) / (a ** 2 + b ** 2)) ** 0.5), 2)
x1  # 这里写答案

0.87

In [20]:
if x1 > 1:
    x2 = x1 * 3 - 5
elif x1 < -1:
    x2 = x1 * 5 + 3
else:
    x2 = x1 + 2
x2

2.87

Q3：计算x1*100所对应的成绩等级，赋值给y
90分以上（含90分）输出A；80分-90分（不含90分）输出B；70分-80分（不含80分）输出C；60分-70分（不含70分）输出D；60分以下输出E。

In [15]:
y = x1 * 100
if y >= 90:
    y = 'A'
elif y >= 80:
    y = 'B'
elif y >= 70:
    y = 'C'
elif y >= 60:
    y = 'D'
else:
    y = 'E'
y

'B'


1. 找出10000以内的完美数，保存到列表L1中。
说明：完美数又称为完全数或完备数，它的所有的真因子（即除了自身以外的因子）的和（即因子函数）恰好等于它本身。
例如：6（6=1+2+3）和28（28=1+2+4+7+14）就是完美数。完美数有很多神奇的特性，有兴趣的可以自行了解。

In [1]:
def find(num):
    lst = [1]
    for j in range(2, num // 2):
        if num % j == 0:
            lst.append(j)
            lst.append(num // j)
    return set(lst)


L1 = [i for i in range(2, 10000) if i == int(sum(find(i)))]
L1  # 开始写作业 加油

[6, 28, 496, 8128]


2. 寻找1000内的水仙花数，并保存到列表L2中；
tips：水仙花数也被称为超完全数字不变数、自恋数、自幂数、阿姆斯特朗数，它是一个3位数，该数字每个位上数字的立方之和正好等于它本身，例如：。

In [47]:
def shui_xian(num):
    if (num // 100) ** 3 + (num // 10 % 10) ** 3 + (num % 10) ** 3 == num:
        return True
    return False


L2 = [x for x in range(153, 1000) if shui_xian(x)]
L2

[153, 370, 371, 407]

3. 写一个程序查询300到500内的回文素数，并保存到列表L3中；
回文素数：即是回文数，又是素数

有15个基督徒和15个非基督徒在海上遇险，为了能让一部分人活下来不得不将其中15个人扔到海里面去，有个人想了个办法就是大家围成一个圈，由某个人开始从1报数，报到9的人就扔到海里面，他后面的人接着从1开始报数，报到9的人继续扔到海里面，直到扔掉15个人。由于上帝的保佑，15个基督徒都幸免于难，问这些人最开始是怎么站的，哪些位置是基督徒哪些位置是非基督徒。输出最后站位，用1表示是基督徒，0表示非基督徒；

In [95]:
def josephus(n, k):
    #n代表总人数，k代表报数的数字
    lst = [x for x in range(1, n + 1)]
    index = 0
    while True:
        temp = lst.pop(0)
        index += 1
        if index == k:
            index = 0
            continue
        lst.append(temp)
        if len(lst) == 15:
            return lst


print(josephus(30, 9))
L1 = ['0'] * 30
for x in josephus(30, 9):
    L1[x - 1] = '1'
L1

[28, 29, 1, 2, 3, 4, 10, 11, 13, 14, 15, 17, 20, 21, 25]


['1',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '0',
 '0',
 '1',
 '1',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '1',
 '1',
 '0']

### 题目2：计算机票票价
某航空公司机票采用浮动制：根据月份和订票张数来确定机票的优惠率：
* 旅游旺季（1月~2月, 7月~10月, 12月），如果订票张数超过15张，票价优惠15%，否则票价优惠5%；
* 其余月份为旅游淡季，旅游淡季时如果订票张数超过20张，票价优惠30%，订票张数5张以下，票价优惠10%，其余情况票价优惠20%。

从键盘输入月份、订票张数和机票原价，输出票价优惠率和应付票款（=机票原价×订票张数×（1-优惠率）），询问是否输入结束，当输入提示为“y”或者“yes”（大小写无关）的时候结束输入。（为了简单，默认输入均正确。）

按照下面程序给的运行结果计算出票款优惠率和应付票款，并保存到L3中：
```
请输入月份：2
请输入订票张数：20
请输入机票原价：2000
票价优惠率：0.15
应付票款：34000.0
输入结束了吗？（y或yes结束，大小写无关，其他继续）：n
请输入月份：
```

In [100]:
def season(mon):
    if mon in [1, 2, 7, 10, 12]:
        return True
    return False


def discount(sea, count):
    if season(sea):
        if count > 15:
            return 0.15
        return 0.05
    if count > 20:
        return 0.3
    elif count < 5:
        return 0.1
    else:
        return 0.2


while True:
    mon = int(input('请输入月份：'))
    num = int(input('请输入订票张数：'))
    price = int(input('请输入机票原价：'))
    con = eval(input('输入结束了吗？（y或yes结束，大小写无关，其他继续）：'))
    print('票价优惠率：', discount(mon, num))
    print('应付票款：', price * num * (1 - discount(mon, num)))
    L2 = [discount(mon, num), price * num * (1 - discount(mon, num))]
    if con == 'yes' or 'y':
        break

票价优惠率： 0.15
应付票款： 34000.0


In [101]:
L2

[0.15, 34000.0]

In [102]:
def is_leap_year(year):
    """
    判断指定的年份是不是闰年
    :param year: 年份
    :return: 闰年返回True平年返回False
    """
    return year % 4 == 0 and year % 100 != 0 or year % 400 == 0


def which_day(year, month, date):
    """
    计算传入的日期是这一年的第几天
    :param year: 年
    :param month: 月
    :param date: 日
    :return: 第几天
    """
    days_of_month = [
        [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31],
        [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        ][is_leap_year(year)]
    total = 0
    for index in range(month - 1):
        total += days_of_month[index]
    return total + date


def main():
    L3 = [which_day(1980, 11, 28), which_day(2020, 1, 1), which_day(2021, 5, 1)]
    print(L3)


if __name__ == '__main__':
    main()

[333, 1, 121]


## 7.30