In [2]:
import numpy as np

2. 打印输出numpy的版本和配置信息 (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.22.4
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

3. 创建一个长度为10的空向量 (★☆☆)

In [4]:
Z = np.zeros(10)
print(Z)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. 如何找到任何一个数组的内存大小？(★☆☆)

In [5]:
Z = np.zeros((10, 10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


5. 如何从命令行得到numpy中add函数的说明文档? (★☆☆)

In [9]:
np.info(np.log)

log(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Natural logarithm, element-wise.

The natural logarithm `log` is the inverse of the exponential function,
so that `log(exp(x)) = x`. The natural logarithm is logarithm in base
`e`.

Parameters
----------
x : array_like
    Input value.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default


6. 创建一个长度为10并且除了第五个值为1的空向量 (★☆☆)

In [92]:
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. 创建一个值域范围从10到49的向量(★☆☆)

In [93]:
Z = np.arange(10, 50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. 反转一个向量(第一个元素变为最后一个) (★☆☆)

In [94]:
Z = np.arange(50)
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

9. 创建一个 3x3 并且值从0到8的矩阵(★☆☆)

In [95]:
Z = np.arange(9).reshape(3, 3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引 (★☆☆)

In [96]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4], dtype=int64),)


11. 创建一个 3x3 的单位矩阵 (★☆☆)

In [97]:
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. 创建一个 3x3x3的随机数组 (★☆☆)

In [98]:
Z = np.random.random((3, 3, 3))
Z

array([[[0.74173432, 0.82960964, 0.67234711],
        [0.48572432, 0.23078882, 0.84525789],
        [0.4209412 , 0.08347323, 0.95363491]],

       [[0.62386533, 0.74901668, 0.4206216 ],
        [0.74997077, 0.06669873, 0.49706766],
        [0.26708748, 0.16675467, 0.58467038]],

       [[0.93048307, 0.07364543, 0.15892682],
        [0.07608121, 0.85814349, 0.29063544],
        [0.03541352, 0.08544966, 0.06766887]]])

13. 创建一个 10x10 的随机数组并找到它的最大值和最小值 (★☆☆)

In [99]:
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0013899472456054829 0.9928134783913268


14. 创建一个长度为30的随机向量并找到它的平均值 (★☆☆)

In [100]:
Z = np.random.random(30)
m = Z.mean()
m

0.45146907170203077

15. 创建一个二维数组，其中边界值为1，其余值为0 (★☆☆)

In [101]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

16. 对于一个存在在数组，如何添加一个用0填充的边界? (★☆☆)

In [102]:
Z = np.ones((5, 5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. 下面表达式运行的结果是什么？(★☆☆)

In [103]:
"""
表达式                             结果
0 * np.nan                        nan
np.nan == np.nan                  False
np.inf > np.nan                   False
np.nan - np.nan                   nan
0.3 == 3 * 0.1                    False
"""

'\n表达式                             结果\n0 * np.nan                        nan\nnp.nan == np.nan                  False\nnp.inf > np.nan                   False\nnp.nan - np.nan                   nan\n0.3 == 3 * 0.1                    False\n'

18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 (★☆☆)

In [104]:
Z = np.diag(1 + np.arange(4), k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. 创建一个8x8 的矩阵，并且设置成棋盘样式 (★☆☆)

In [105]:
Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [106]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


21. 用tile函数去创建一个 8x8的棋盘样式矩阵(★☆☆)

In [107]:
Z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

22. 对一个5x5的随机矩阵做归一化(★☆☆)
    (x - min) / (max - min))

In [108]:
Z = np.random.random((5, 5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin) / (Zmax - Zmin)
Z

array([[0.53613043, 0.9557931 , 0.68321498, 0.76671593, 0.51349503],
       [0.70264988, 0.97210167, 0.23819194, 1.        , 0.46597804],
       [0.95308789, 0.81921781, 0.5433075 , 0.9811056 , 0.47178444],
       [0.48837442, 0.67062607, 0.24311072, 0.17399402, 0.31832661],
       [0.83588972, 0.        , 0.47173648, 0.29376291, 0.60572347]])

23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？(★☆☆)

In [109]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

C:\Users\Admin\AppData\Local\Temp\ipykernel_2528\2830546906.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？(★☆☆)

In [110]:
Z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
Z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

25. 给定一个一维数组，对其在3到8之间的所有元素取反 (★☆☆)

In [111]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

26. 下面脚本运行后的结果是什么? (★☆☆)

In [112]:
print(sum(range(5), -1))  #10-1

9


27. 考虑一个整数向量Z,下列表达合法的是哪个? (★☆☆)

In [113]:
'''
Z**Z                        True
2 << Z >> 2                 False
Z <- Z                      True
1j*Z                        True  #复数
Z/1/1                       True
Z<Z>Z                       False
'''

'\nZ**Z                        True\n2 << Z >> 2                 False\nZ <- Z                      True\n1j*Z                        True  #复数\nZ/1/1                       True\nZ<Z>Z                       False\n'

28. 下面表达式的结果分别是什么？(★☆☆)

In [114]:
'''
np.array(0) / np.array(0)                           nan
np.array(0) // np.array(0)                          0
np.array([np.nan]).astype(int).astype(float)        -2.14748365e+09
'''

'\nnp.array(0) / np.array(0)                           nan\nnp.array(0) // np.array(0)                          0\nnp.array([np.nan]).astype(int).astype(float)        -2.14748365e+09\n'

29. 如何从零位开始舍入浮点数组？(★☆☆)

In [115]:
Z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ -2.  -8. -10.   7.   3.   7.   5.   1.  -3.  -4.]


30. 如何找出两个数组公共的元素? (★☆☆)

In [116]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(np.intersect1d(Z1, Z2))

[2 9]


31. 如何忽略所有的 numpy 警告(尽管不建议这么做)? (★☆☆)

In [117]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# 另一个等价的方式， 使用上下文管理器（context manager）
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0
Z

array([inf])

32. 下面的表达式是否为真? (★☆☆)

In [118]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_2528\2961820512.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

33. 如何获得昨天，今天和明天的日期? (★☆☆)

In [119]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print('昨天:%s, 今天：%s, 明天:%s' % (yesterday, today, tomorrow))

昨天:2022-06-01, 今天：2022-06-02, 明天:2022-06-03


34. 怎么获得所有与2016年7月的所有日期? (★★☆)

In [120]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

35. 如何计算 ((A+B)*(-A/2)) (不使用中间变量)? (★★☆)

In [121]:
A = np.ones(3) * 1
print(A)
B = np.ones(3) * 1
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
A

[1. 1. 1.]


array([-1., -1., -1.])

36. 用4种不同的方法提取随机数组中的整数部分 (★★☆)

In [122]:
Z = np.random.uniform(0, 10, 10)
print(Z - Z % 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[9. 8. 9. 5. 8. 1. 4. 2. 5. 6.]
[9. 8. 9. 5. 8. 1. 4. 2. 5. 6.]
[9 8 9 5 8 1 4 2 5 6]
[9. 8. 9. 5. 8. 1. 4. 2. 5. 6.]


37. 创建一个5x5的矩阵且每一行的值范围为从0到4 (★★☆)

In [123]:
Z = np.zeros((5, 5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

38. 如何用一个生成10个整数的函数来构建数组 (★☆☆)

In [124]:
def generate():
    for x in range(10):
        yield x


Z = np.fromiter(generate(), dtype=float, count=-1)
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

39. 创建一个大小为10的向量， 值域为0到1，不包括0和1 (★★☆)

In [125]:
Z = np.linspace(0, 1, 12, endpoint=True)[1: -1]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

40. 创建一个大小为10的随机向量，并把它排序 (★★☆)

In [126]:
Z = np.random.random(10)
Z.sort()
Z

array([0.34782763, 0.36286367, 0.44087204, 0.46346891, 0.54471284,
       0.57116385, 0.62759152, 0.63499268, 0.76266758, 0.93890779])

41.  对一个小数组进行求和有没有办法比np.sum更快? (★★☆)

In [127]:
Z = np.arange(10)
np.add.reduce(Z)

45

42. 如何判断两和随机数组相等 (★★☆)

In [128]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# 假设array的形状(shape)相同和一个误差容限（tolerance）
equal = np.allclose(A, B)
print(equal)

# 检查形状和元素值，没有误差容限（值必须完全相等）
equal = np.array_equal(A, B)
print(equal)

False
False


43. 把数组变为只读 (★★☆)

In [129]:
Z = np.zeros(5)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

44. 将一个10x2的笛卡尔坐标矩阵转换为极坐标 (★★☆)

In [130]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.54378493 0.20451339 1.28599693 0.8470886  0.17964216 1.22940496
 1.19397987 1.05715876 0.84789306 0.78540639]
[1.18479667 1.55331523 0.84482291 0.99076879 0.83849454 0.67225903
 0.84937197 0.34698474 1.24753426 0.71906239]


45. 创建一个大小为10的随机向量并且将该向量中最大的值替换为0(★★☆)

In [131]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
Z

array([0.12590935, 0.81643615, 0.209797  , 0.        , 0.64439017,
       0.2694235 , 0.39470173, 0.12981643, 0.59294596, 0.65214869])

46. 创建一个结构化数组，其中x和y坐标覆盖[0, 1]x[1, 0]区域 (★★☆)

In [132]:
Z = np.zeros((5, 5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

47. 给定两个数组X和Y，构造柯西(Cauchy)矩阵C () (★★☆)

In [133]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)
print(np.linalg.det(C))  # 计算行列式

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.163637117973


48. 打印每个numpy 类型的最小和最大可表示值 (★★☆)

In [134]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. 如何打印数组中所有的值？(★★☆)

In [136]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16, 16))
print(Z)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

50. 如何在数组中找到与给定标量接近的值? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(Z - v)).argmin()
print(Z[index])