# NumPy.ndarray中的运算

给定一个向量，让向量中的每一个数乘以2  
  
a = (0,1,2)    

a*2 = (0,2,4)

对于这种操作，Python 的列表是如何支持的？

In [1]:
n = 10
L = [i for i in range(n)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
2 * L # 将两个L首尾衔接，并不是对其中每一个元素都乘以2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
A = [] # 设置一个空列表
for e in L:
    A.append(e*2)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
n = 1000000
L = [i for i in range(n)]

In [4]:
%%time
A = []
for e in L:
    A.append(e*2)

CPU times: total: 93.8 ms
Wall time: 94 ms


In [5]:
%%time
A = [2*i for i in range(1000000)]

CPU times: total: 62.5 ms
Wall time: 51 ms


In [8]:
import numpy as np

In [9]:
L = np.arange(n)

In [10]:
%%time
A = np.array(2*i for i in L)

CPU times: total: 15.6 ms
Wall time: 7 ms


使用 numpy 中的 ndarray，速度比 python 中的列表大幅提高

numpy.ndarray 支持向量运算，可以直接使用数乘的方式返回新数组

In [11]:
%%time
A = 2 * L

CPU times: total: 0 ns
Wall time: 1.99 ms


In [4]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

## 通用函数 Universal Functions  

Numpy 将 array 直接当做向量或者矩阵来看待，支持很多向量、矩阵的数学运算，且运算极快。在 Numpy 中进行的这些向量、矩阵运算统称为 Universal functions。

In [13]:
X = np.arange(1,16).reshape((3,5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

* 加减乘除基本运算

In [13]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [14]:
X - 1 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [20]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [25]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [26]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

* 幂运算

In [27]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

* 取余

In [28]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

* abs 取绝对值

In [29]:
np.abs(X) # 求绝对值

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

* sin 取正弦函数

In [30]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

* cos 取余弦函数

In [31]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

* tan 取正切

In [32]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

* exp 取 e 的 x 次方

In [33]:
np.exp(X) # e的X次方

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

* power 求x的n次方

In [34]:
np.power( X,3)

array([[   1,    8,   27,   64,  125],
       [ 216,  343,  512,  729, 1000],
       [1331, 1728, 2197, 2744, 3375]], dtype=int32)

In [35]:
X**3

array([[   1,    8,   27,   64,  125],
       [ 216,  343,  512,  729, 1000],
       [1331, 1728, 2197, 2744, 3375]], dtype=int32)

* log 以 e 为底求对数

In [36]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

* log2 以2为底

In [37]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

* log10 以10为底

In [38]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵运算

In [14]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [15]:
B = np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [41]:
A + B # 对应元素相加

array([[10, 11],
       [12, 13]])

In [42]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

**注意**： A * B 返回的是两个矩阵对应元素相乘的结果，并不是矩阵乘法的定义。

In [43]:
A * B # A和 B对应元素相乘的结果

array([[ 0, 10],
       [20, 30]])

In [44]:
A/B 

array([[0. , 0.1],
       [0.2, 0.3]])

### 矩阵乘法

如何用numpy实现真正的矩阵乘法？

In [16]:
A = np.arange(1,7).reshape(2,3)
B = np.arange(7,13).reshape(3,2)

In [50]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
B

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [52]:
A.dot(B) # 矩阵乘法

array([[ 58,  64],
       [139, 154]])

In [53]:
np.dot(A,B)

array([[ 58,  64],
       [139, 154]])

但是大家都知道，矩阵相乘是有方向的，因此建议大家使用 A.dot(B)的形式，就知道是A矩阵作用于B矩阵，因此也是A乘以B。

### 矩阵的转置

In [62]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

**注意**： 矩阵的运算对矩阵的维度是有要求的

In [17]:
C = np.full((3,3),666)
C

array([[666, 666, 666],
       [666, 666, 666],
       [666, 666, 666]])

In [65]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
A + C

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [18]:
A.dot(C)

array([[3996, 3996, 3996],
       [9990, 9990, 9990]])

矩阵的运算要保证矩阵之间维度匹配

## 矩阵和向量的运算

In [31]:
v = np.array([1,2])
v

array([1, 2])

In [20]:
A = np.arange(1,5).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [28]:
v + A 

array([[2, 4],
       [4, 6]])

**注意**：虽然在数学上我们没有定义一个向量和一个矩阵之间如何进行加法运算，但是在 numpy 里向量和矩阵的加法就是向量和矩阵的每一行的对应位置元素做加法。

### Numpy 数组的广播机制  

Numpy 允许大小不同的数组进行对应位置元素的加减乘除等运算。将维度小的数组进行扩展，叫做Numpy数组的广播机制。

<img src='resource/broadcasting.png'>

第一行：向量和标量相加：将标量扩展成维度相同的向量。  
第二行：矩阵和向量相加：将向量扩展成维度相同的矩阵。  
第三行：列向量和行向量相加，将彼此都进行另一个维度的扩展。

In [24]:
V1 = np.arange(0,15).reshape(3,5)
V2 = np.arange(0,15).reshape(5,3)
V1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
V2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [29]:
V1 + V2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

* 如果这样做在数学上不合理，不想使用广播机制，那么可以手动使用 vstack 方法，将向量v叠加，变得和A一样维度再进行计算

In [32]:
v

array([1, 2])

In [65]:
A

array([[1, 2],
       [3, 4]])

In [67]:
A.shape[0]

2

In [33]:
A.shape

(2, 2)

In [34]:
V = np.vstack([v] * A.shape[0])

In [35]:
V

array([[1, 2],
       [1, 2]])

In [69]:
V + A

array([[2, 4],
       [4, 6]])

由于这样的堆叠在 numpy 中经常使用，因此 numpy 提供了另一个方法，tile，允许我们对向量进行堆叠

In [36]:
np.tile(v,(2,1)) #行方向复制2，列方向复制1

array([[1, 2],
       [1, 2]])

In [37]:
v

array([1, 2])

In [38]:
A

array([[1, 2],
       [3, 4]])

In [39]:
v * A # v向量和A中的每一个向量做元素之间的乘法

array([[1, 4],
       [3, 8]])

In [42]:
v

array([1, 2])

In [43]:
A

array([[1, 2],
       [3, 4]])

In [44]:
v.dot(A)

array([ 7, 10])

numpy 会自动判断行向量还是列向量

In [45]:
A.dot(v) # 向量的运算，numpy会自动判断是行向量还是列向量

array([ 5, 11])

### 矩阵的逆

In [46]:
A

array([[1, 2],
       [3, 4]])

linalg —— linear algebra 的缩写

In [47]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [48]:
invA = np.linalg.inv(A)

In [74]:
A.dot(invA)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [75]:
invA.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [49]:
X = np.arange(16).reshape(2,8)
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [50]:
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

### 伪逆矩阵  

由于不是所有的矩阵都存在逆矩阵，比如奇异矩阵和非方阵，那么实际上我们使用伪逆矩阵更多一些。

In [51]:
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [52]:
pinvX = np.linalg.pinv(X)

In [53]:
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -6.93889390e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [81]:
pinvX.shape

(8, 2)

In [54]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.91433544e-16],
       [ 1.33226763e-15,  1.00000000e+00]])