# Numpy中的统计函数

In [1]:
import numpy as np

In [8]:
# 生成 0 和 1 之间的一维数组，数组长度为100
L = np.random.random(100)
L

array([0.7157662 , 0.17376832, 0.68476723, 0.03061084, 0.69964662,
       0.66632883, 0.90941719, 0.03089116, 0.58895654, 0.3254724 ,
       0.09482103, 0.97586596, 0.22401293, 0.8236221 , 0.5535622 ,
       0.89602008, 0.99472808, 0.77931044, 0.07616024, 0.76175413,
       0.84021593, 0.58842638, 0.38697226, 0.57916487, 0.97793957,
       0.91772343, 0.56947508, 0.84200279, 0.49999271, 0.4634029 ,
       0.33218187, 0.55381984, 0.13679746, 0.78240055, 0.94659399,
       0.73928513, 0.03524445, 0.31901658, 0.28505239, 0.13088562,
       0.668162  , 0.38669414, 0.29365669, 0.67999821, 0.22253177,
       0.35583432, 0.38250584, 0.61695634, 0.20998525, 0.34495778,
       0.62055722, 0.80512839, 0.3103981 , 0.99231645, 0.86177005,
       0.16586194, 0.18928869, 0.65155504, 0.37776897, 0.27829496,
       0.98331015, 0.09028312, 0.06986379, 0.28286552, 0.73691115,
       0.00373658, 0.16260102, 0.19282323, 0.53774576, 0.21895957,
       0.91307869, 0.75884372, 0.56268169, 0.68662571, 0.63456

In [9]:
sum(L)

50.61623338333427

In [10]:
np.sum(L)

50.616233383334276

In [2]:
big_array = np.random.random(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

43.8 ms ± 263 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
313 µs ± 4.18 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


跑了7次，平均每次跑了（10-1000个循环）

In [3]:
%timeit np.min(big_array)

240 µs ± 4.91 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [13]:
np.max(big_array)

0.9999994296033643

也可以使用面向对象的方式去调用

In [4]:
%timeit big_array.min()

235 µs ± 6.09 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [15]:
big_array.max()

0.9999994296033643

In [16]:
big_array.sum()

500105.2871208608

两种调用聚合方法：np.method() or arr.method()  
np.method()的方法更全

In [5]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
np.sum(X)

120

聚合运算默认对所有元素进行聚合，不管你是一维数组还是二维数组。

In [19]:
np.sum(X,axis=0) # 沿着行的方向进行计算，求的是每一列的和

array([24, 28, 32, 36])

In [20]:
np.sum(X,axis=1) # 沿着列的方向进行计算，求的是每一行的和

array([ 6, 22, 38, 54])

In [7]:
np.prod(X) # 所有元素的乘积

0

In [22]:
np.prod(X+1)

2004189184

In [8]:
np.mean(X)

7.5

In [24]:
np.median(X) # 求中位数

7.5

**注意**：尽管我们通常使用均值来描述样本的总体特征，但是均值对异常点非常敏感。

In [25]:
v = np.array([1,1,2,2,10]) # 10 是和其他样本差距非常大的点
np.mean(v)

3.2

In [26]:
np.median(v)

2.0

常用的百分位点

In [22]:
for percent in [0,25,50,75,100]: # 常用的百分位点
    print(np.percentile(big_array,percent))

2.131410019146074e-06
0.2502246946791415
0.500092817464117
0.74972946418758
0.9999992064616408


* var 方差

In [23]:
np.var(big_array) # 求方差

0.08326558779775199

* std 标准差

In [24]:
np.std(big_array) # 求标准差

0.28855777202798055

In [25]:
x = np.random.normal(0,1,size=1000000)
x

array([ 0.00930458,  1.40233881, -0.87303022, ...,  0.17681353,
       -0.25653976, -1.03068073])

In [26]:
np.mean(x)

-0.001289958699101101

In [27]:
np.std(x)

0.9998665529531698

### 获取索引 —— arg运算

In [37]:
x = np.random.randint(0,1000,100)
x

array([473, 208, 215, 917, 577, 616, 927, 920, 280, 871, 669, 650,  42,
       767, 113, 367, 241, 877, 264, 487, 776, 452, 174, 110, 953, 997,
       433, 321,  54, 213, 112, 390, 409, 588, 642, 579, 911, 108, 288,
       686, 170, 894, 960, 888, 908, 141, 164, 545, 819, 402, 988,  17,
       940, 104, 271,  47, 463, 852, 393, 423, 570, 931,  30, 279, 829,
       542, 651, 650, 432, 910, 991, 968, 956, 924, 576, 368,  34, 889,
       234, 937, 840, 102, 744, 310, 844, 932, 492, 464, 181, 602, 100,
       445, 718, 331, 303, 344, 587, 898, 412, 698])

In [38]:
np.min(x)

17

获取最小值所在的索引

In [39]:
np.argmin(x) # x的最小值所在的索引

51

In [41]:
np.argmax(x) # x 的最大值所在的索引

25

In [42]:
x[25]

997

In [43]:
np.max(x)

997

## 排序

In [9]:
x = np.arange(16)

In [45]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

* np.random.shuffle(x) 对 x 进行乱序

In [46]:
np.random.shuffle(x)

In [47]:
x

array([ 4,  2, 14,  7, 12, 10,  6,  8,  1,  5, 11,  3,  9, 15,  0, 13])

In [48]:
np.sort(x) # 没有改变x本身的顺序

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
x

array([ 4,  2, 14,  7, 12, 10,  6,  8,  1,  5, 11,  3,  9, 15,  0, 13])

In [50]:
x.sort() # x本身被排好序

In [51]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
X = np.random.randint(10,size=(4,4))

In [11]:
X

array([[4, 6, 9, 2],
       [1, 3, 0, 6],
       [1, 9, 6, 5],
       [0, 4, 5, 8]])

In [12]:
np.sort(X) # 默认结果，将每一行按照顺序排序

array([[2, 4, 6, 9],
       [0, 1, 3, 6],
       [1, 5, 6, 9],
       [0, 4, 5, 8]])

In [13]:
np.sort(X,axis=1) # 沿着列的方向进行排序，也就是每一行是有序的，axis默认值是1

array([[2, 4, 6, 9],
       [0, 1, 3, 6],
       [1, 5, 6, 9],
       [0, 4, 5, 8]])

In [15]:
np.sort(X,axis=0)

array([[0, 3, 0, 2],
       [1, 4, 5, 5],
       [1, 6, 6, 6],
       [4, 9, 9, 8]])

In [58]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:
np.random.shuffle(x)

In [60]:
x

array([ 2, 11,  4,  6,  7,  8, 14,  9, 15,  5, 12,  0,  1, 10,  3, 13])

In [61]:
np.argsort(x) # 存放的是排列有序的元素的索引

array([11, 12,  0, 14,  2,  9,  3,  4,  5,  7, 13,  1, 10, 15,  6,  8],
      dtype=int64)